[versions]
lifecycle = "2.8.4"
agp = "8.5.2"
kotlin = "2.0.20"
composeBom = "2024.10.00"

[plugins]
compose-plugin = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[libraries]
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.3" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }

# Compose compiler plugin (required for Kotlin 2.0+)

[versions.room]
room = "2.6.1"

[libraries.androidx-room-runtime]
module = "androidx.room:room-runtime", version.ref = "room.room"
[libraries.androidx-room-ktx]
module = "androidx.room:room-ktx", version.ref = "room.room"
[libraries.androidx-room-compiler]
module = "androidx.room:room-compiler", version.ref = "room.room"
